# Generated by Django 5.0.6 on 2024-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, default='', verbose_name='Подробное описание'),
        ),
    ]
