# Generated by Django 5.0.6 on 2024-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_task_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Подробное описание'),
        ),
    ]
