# Generated by Django 5.0.6 on 2024-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_task_status_alter_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(db_table='tasks_types', related_name='tasks', to='webapp.type', verbose_name='Типы'),
        ),
    ]
