# Generated by Django 5.0.6 on 2024-07-21 16:08

from django.db import migrations


def fill_tasks_project(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    Project = apps.get_model('webapp.Project')

    project = Project.objects.first()

    Task.objects.all().update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_task_project'),
    ]

    operations = [
        migrations.RunPython(fill_tasks_project, migrations.RunPython.noop)
    ]
