# Generated by Django 5.0.6 on 2024-07-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_user_in_project', 'Добавить пользователя в проект'), ('delete_user_from_project', 'Удалить пользователя из проекта')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
